version: '3.7'
services:
  ##### MQTT
    mqtt:
      image: eclipse-mosquitto:latest
      container_name: mqtt-test
      ports:
        - 1883:1883
      volumes:
        - './mosquitto/config:/mosquitto/config'
        - './mosquitto/data:/mosquitto/data'
        - './mosquitto/log:/mosquitto/log'